# Generated by Django 6.1 on 2026-08-16 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0002_studentskill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('evidence_type', models.CharField(choices=[('coursework', 'Coursework'), ('project', 'Project'), ('competition', 'Competition'), ('credential', 'Micro-Credential'), ('assessment', 'Practical Assessment'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('issuing_organization', models.CharField(blank=True, max_length=200)),
                ('evidence_url', models.URLField(blank=True)),
                ('verification_status', models.CharField(choices=[('self_declared', 'Self Declared'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('partially_verified', 'Partially Verified'), ('rejected', 'Rejected')], default='self_declared', max_length=30)),
                ('verification_score', models.PositiveIntegerField(default=0, help_text='Verification confidence from 0 to 100.')),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='evidence', to='skills.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
