# Generated by Django 6.1 on 2026-08-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='verification_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
